### ISSUE TITLE
YamlPath not using list node names.

### ISSUE THREAD

**Issue by jamesoneill** [yaml-path/YamlPath#96]
I have some YAMLPATH with values as described.
[applications.name=my-app, applications.routes[0].route=example.com, applications.routes[1].route=www.example.com/foo, applications.routes[2].route=tcp-example.com:1234, applications.env.greeting=hello, applications.env.BUNDLE_WITHOUT=test:development, stuff=other]

This is my base yaml file:
 - applications:
      name: my-app
      routes:
        - route: example.com
        - route: www.example.com/foo
        - route: tcp-example.com:1234
      env:
        greeting: hello
        BUNDLE_WITHOUT: test:development
    stuff: other

When i apply my YAMLPATH using write method i get: 

  - applications:
      name: my-app
      routes:
        - example.com
        - www.example.com/foo
        - tcp-example.com:1234
      env:
        greeting: hello
        BUNDLE_WITHOUT: test:development
    stuff: other

Im wondering why the route name gets dropped completely it feels like this should replace the routes element name route as well as the value.

**Comment by Sgitario** [comment]
Thanks for reporting!
Can you share the `write` call you are doing (with the arguments) to help me understand what is going on?

**Comment by jamesoneill** [comment]
Yes of course, 

data in this case is the serialised Map below: 
[applications.name=my-app, applications.routes[0].route=example.com, applications.routes[1].route=www.example.com/foo, applications.routes[2].route=tcp-example.com:1234, applications.env.greeting=hello, applications.env.BUNDLE_WITHOUT=test:development, stuff=other]


for(Map.Entry<String, String> entry: data.entrySet())
{
    yaml.write(entry.getKey(), entry.getValue());
}

**Comment by Sgitario** [comment]
Yet I can't see what is going on. 
Can you share a simple reproducer please?

**Comment by Sgitario** [comment]
> Yet I can't see what is going on. Can you share a simple reproducer please?

Never mind. I think I was able to reproduce it.

**Comment by Sgitario** [comment]
https://github.com/yaml-path/YamlPath/pull/97 should fix this issue.
